<?xml version="1.0" encoding="UTF-8"?><testrun name="Tests" project="PracticaArrays" tests="2" started="2" failures="1" errors="0" ignored="0">
  <testsuite name="tests.Tests" time="0.029" displayname="Tests" uniqueid="[engine:junit-jupiter]/[class:tests.Tests]">
    <testcase name="testMinimaNota" classname="tests.Tests" time="0.013" displayname="testMinimaNota()" uniqueid="[engine:junit-jupiter]/[class:tests.Tests]/[method:testMinimaNota()]"/>
    <testcase name="testMinimaNota2" classname="tests.Tests" time="0.015" displayname="testMinimaNota2()" uniqueid="[engine:junit-jupiter]/[class:tests.Tests]/[method:testMinimaNota2()]">
      <failure>
        <expected>El número 11 no está entre 0 y 10</expected>
        <actual>El número 11.0 no está entre 0 y 10</actual>
        org.opentest4j.AssertionFailedError: expected: &lt;El número 11 no está entre 0 y 10&gt; but was: &lt;El número 11.0 no está entre 0 y 10&gt;&#13;
	at org.junit.jupiter.api.AssertionFailureBuilder.build(AssertionFailureBuilder.java:151)&#13;
	at org.junit.jupiter.api.AssertionFailureBuilder.buildAndThrow(AssertionFailureBuilder.java:132)&#13;
	at org.junit.jupiter.api.AssertEquals.failNotEqual(AssertEquals.java:197)&#13;
	at org.junit.jupiter.api.AssertEquals.assertEquals(AssertEquals.java:182)&#13;
	at org.junit.jupiter.api.AssertEquals.assertEquals(AssertEquals.java:177)&#13;
	at org.junit.jupiter.api.Assertions.assertEquals(Assertions.java:1141)&#13;
	at tests.Tests.testMinimaNota2(Tests.java:23)&#13;
	at java.base/java.lang.reflect.Method.invoke(Method.java:580)&#13;
	at java.base/java.util.ArrayList.forEach(ArrayList.java:1596)&#13;
	at java.base/java.util.ArrayList.forEach(ArrayList.java:1596)&#13;
&#13;

      </failure>
    </testcase>
  </testsuite>
</testrun>
